version: '3'
services:
  nginx:
    image: nginx:latest
    networks:
      - mynetwork
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  redis:
    image: redis:latest
    networks:
      - mynetwork
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mynetwork
    depends_on:
      - redis
networks:
  mynetwork: